name: Build and push the release image

on:
    push:
        branches:
            - testing-release

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Extract branch name
              shell: bash
              run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
            - run: sudo ./dev-scripts/build_and_push_release.sh
